// GENERATED by scripts/generate-arbitrum-catalog.mjs from docs/Reports/ARBITRUM-ADDRESS-MANIFEST.json.
// Do not hand-edit addresses/decimals. Re-run the generator + commit when the manifest changes.
// [CHORE-47C-ARBITRUM-CATALOG] Launch catalog = the 5 Chainlink-feed-covered manifest tokens
// (owner decision, L-01 adjudication). wstETH is intentionally excluded (deferred post-activation).
//
// [CHORE-ARBITRUM-UI-POLISH] `verified: true` on all 5 mirrors the manifest's per-entry
// `ok: true` — each address was cross-checked symbol+decimals on 2 independent RPCs
// (docs/Reports/ARBITRUM-ADDRESS-MANIFEST.json). Not pipeline-verified (no generated
// token-catalog.42161.json yet), but manifest-verified the same way the launch set itself
// was validated; see tokens.ts for how this flows into the ✓ badge.

export interface ArbitrumManifestToken {
  key: string
  address: `0x${string}`
  decimals: number
  verified: boolean
}

export const ARBITRUM_MANIFEST_TOKENS: ArbitrumManifestToken[] = [
  { key: 'WETH', address: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', decimals: 18, verified: true },
  { key: 'USDC', address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831', decimals: 6, verified: true },
  { key: 'USDT', address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9', decimals: 6, verified: true },
  { key: 'DAI', address: '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1', decimals: 18, verified: true },
  { key: 'WBTC', address: '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', decimals: 8, verified: true },
]
